### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by MicTott** [LieberInstitute/BLA_crossSpecies#2]
# Roadmap for normalization and Dimensionality Reduction

## Step 1: Subset genes to only 1:1 orthologs

- [X] Convert baboon and macaque genes to human while retaining only 1:1 orthologs using `orthogene::convert_orthologs` with `non121_strategy="drop_both_species"`
- [X] Get common NHP orthologs, Drop orthologs not in human dataset to get final list of common orthologs
- [X] Subset human, baboon, and macaque SCEs to only common 1:1 orthologs

## Step 2: Log normalization and scale factos across species

Within each species ...
- [X] Deal with compositional biases by pre-clustering using `quickCluster`. This avoids the assumption that most genes are non-DE across the population
- [X] Calculate scaling factors using `computeSumFactors`
- [X] Log normalize the count data with 'logNormCounts'
