### ISSUE TITLE
Batch correction

### ISSUE THREAD

**Issue by MicTott** [LieberInstitute/BLA_crossSpecies#3]
# Roadmap for batch correction
Batch correction here is tricky as we need to correct for both `Samples` within species and then merge the data across `Species.` For this, I think it makes the most sense to correct for `Samples` wthin species first, and then merge and correct for differences across the `Species` datasets.

I will perform testing using both MNN and Seurat as per [this paper.](https://www.nature.com/articles/s41467-023-41855-w)

### 1 . Correct samples within species

- [x] Remove lowly expressed genes: Keep only those genes that have at least 1 UMI in at least 5% of the data

Within each species...
- [x] Because this is a very large dataset and each dataset have a different number of total cells, let's randomly subset 10k cells from each species. Do not combine subsets. 

**For Harmony and MNN**
- [ ] ~Compute approx. GLM-PCA using null residuals according to [this workflow](https://www.stephaniehicks.com/biocdemo/articles/Demo.html): 'scry::nullResiduals' + 'scater::runPCA with chosen HVGs. n=50 components~

- [ ] ~Compute UMAP on using `scater::runUMAP` on uncorrected GLM-PCA dimred~

- [ ] ~Perform batch correction on `sample_id` using batchelor::reducedMNN with GLM-PCA dimred; add to reducedDims~
- [ ] ~Compute UMAP on using `scater::runUMAP` on MNN corrected GLM-PCA dimred~

- [ ] ~Perform batch correction on 'sample_id' using 'Harmony::RunHarmony' with GLM-PCA dimred~
- [ ] ~Compute UMAP on using `scater::runUMAP` on Harmony corrected GLM-PCA dimred~

- [ ] ~Visualize batch correction results by plotting and printing uncorrected, MNN, and Harmony corrected UMAPs colored by `sample_id`~

> GLM-PCA resulted in "stringy" clusters no matter how I adjusted the hyperparameters. Because I previously determined that Seurat was the best for clustering, I moved forward with that (which uses Pearson residuals from negative binomial regression (`sctransform`) instead of GLM-PCA)

**Seurat CCA**
- [X] Perform batch correction using Seurat
